plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gztxt.piweb'
    compileSdk 34

    defaultConfig {
        applicationId "com.gztxt.piweb"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "2.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
